spring.datasource.url=jdbc:h2:file:./data/setup_gamer
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=0103

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true